### ISSUE TITLE
keep Propertienames of Arrayfied StorageObjects

### ISSUE THREAD

**Issue by SvenDeKa** [ervaude/json_example#1]
As you're already extending JsonView for the Configuration, you could also change the behaviour of transformValues() in order to toArray all $values being an instance of StorageObject:

```
protected function transformValue($value, array $configuration)
    {
        if($value instanceof \TYPO3\CMS\Extbase\Persistence\ObjectStorage) {
            $value = $value->toArray();
        }
...
rest of the original Function.
}
```

what do you think?

BTW: thx for the HowTo ;)

**Comment by ervaude** [comment]
I guess that would be clever! It is highly unlikely that you need the ObjectStorage hashes as object keys in your JSON.
👍

**Comment by ervaude** [comment]
Thanks for the hint. I also udpated the blog post.
