### ISSUE TITLE
Typo3 likes to insert "<!-- Parsetime: ... -->" into output

### ISSUE THREAD

**Issue by ghost** [ervaude/json_example#3]
Hi, 
very nice example, thank you!

It should be noted that Typo3 inserts "Parsetime: " comments into output when in Debug mode - even when using the JsonView. This invalidates the JSON!

You should put         

```
// no parsetime debug output with this action
$GLOBALS['TSFE']->config['config']['debug'] = 0;
```

in all actions to suppress that.

If you don't, you can end up with "JSON"-output like
```
"test"
<!-- Parsetime: 311ms -->
```

**Comment by ervaude** [comment]
Yes.

But this is done in the TypoScript configuration of the PageType that handle the requests:

```
api_tag = PAGE
api_tag {
	config {
		disableAllHeaderCode = 1
		debug = 0
		no_cache = 1
	}
	typeNum = 1452982642
	10 < tt_content.list.20.jsonexample_json_tag
}
```

**Comment by ghost** [comment]
Ah, I see. Sorry,I missed that you went the typeNum-way with TS-config. I used the JsonView with typoscript_rendering.
