### ISSUE TITLE
Page type not loaded

### ISSUE THREAD

**Issue by vojtasvoboda** [ervaude/json_example#4]
Thanks for json-example extension in advance!

I would like to ask - I'm following blog post and do everything step by step. But I'm stuck in the middle of writing TC and opening page with `&type=1452982642` param.

I've installed your plugin, but which page type should I select?

<img width="272" alt="snimek obrazovky 2018-03-21 v 15 48 18" src="https://user-images.githubusercontent.com/374917/37717448-de5ff51c-2d20-11e8-9292-ea0487a1dfb5.png">

When I select "Standard" type and opens page with `type` param, it gives me:

`The page is not configured! [type=1452982642][]. This means that there is no TypoScript object of type PAGE with typeNum=1452982642 configured.`

**Comment by ervaude** [comment]
Hi,
the doktype of the page does not matter as the `type=1452982642` just concerns the frontend output.

**Make sure you included the static TypoScript** of this extension in your sys_template (the template module in the Backend). After that if you perform a request to your website with `?type=1452982642&tx_jsonexample_json_tag[tag]=1` you should see JSON output (if you created at least on record)

**Comment by vojtasvoboda** [comment]
Looks like there is no TypoScript with `json_example` string. Could you help me how to include static TypoScript of `json_example` extension?

**Comment by vojtasvoboda** [comment]
I've got it! This small step - including TypoScript to sys_template should be definitely mentioned in a blog post! It takes me 4 hours to figure it out.

<img width="444" alt="snimek obrazovky 2018-03-23 v 11 35 56" src="https://user-images.githubusercontent.com/374917/37824944-8352b8e8-2e8e-11e8-9706-39177f17ffab.png">

<img width="249" alt="snimek obrazovky 2018-03-23 v 11 37 24" src="https://user-images.githubusercontent.com/374917/37824965-9501bbd4-2e8e-11e8-9577-c6a230a1ea96.png">

**Comment by ervaude** [comment]
Ah, sorry, I forgot to tell you where to do it. It is mentioned in the Readme.md of this extension and is kind of well-known for TYPO3 extensions. You will meet this a lot that an extension needs its TypoScript loaded. There are several ways to do it, including the static template in the template module is only one of them.

Glad you found out by yourself, though.

**Comment by vojtasvoboda** [comment]
Ok thanks! Loading page with`?type=1452982642` is ok, but when I use: `?type=1452982642&tx_jsonexample_json_tag[action]=show&tx_jsonexample_json_tag[tag]=1` to get only one tag, TYPO3 returns me:

<img width="650" alt="snimek obrazovky 2018-03-23 v 13 39 45" src="https://user-images.githubusercontent.com/374917/37829589-e197ed36-2e9f-11e8-99be-0e03d7e0b954.png">

**Comment by ervaude** [comment]
Well yes. This extension was developed using TYPO3 7LTS and you seem to use at least 8LTS. There was a change in the default behaviour for extbase plugins that now a cHash (cache hash) is requiered for every request.

You can disable this behavior for your API (since cacheing is deactivated for the page type anyway) with `plugin.tx_jsonexample.features.requireCHashArgumentForActionArguments = 0` in your TypoScript (setup).

Please try this, I did not test it but it should work.

**Comment by vojtasvoboda** [comment]
Yes it works! You can now release json_extension for TYPO3 8LTS :-) Thank you again and sorry for newbie questions :-)
