### ISSUE TITLE
Installation via composer (in ddev)?

### ISSUE THREAD

**Issue by rowild** [ervaude/json_example#8]
I tried to install this ext via composer in my ddev TYPo3 10, but to no avail. I first downloaded the ext, then moved it to "packages", then added these scripts to my composer.json:

```json
	"repositories": [
		{
			"type": "path",
			"url": "./packages/json_example",
			"options": {
				"symlink": true
			}
		}
	],
	"require": {
		"ervaude/json-example": "dev-master",
```

Unfortunately this does not work. Any ideas what I am doing wrong?
Also, wouldn't the description of the installation be a good addition to the readme?

**Comment by ervaude** [comment]
Try to require it as 

`"danielgoerz/json-example": "*",`

or

`"danielgoerz/json-example": "@dev",`

**Comment by rowild** [comment]
Yes, I realised yesterday that I need to use "danielgoerz" instead of "ervaude". Thank you!
